# Generated by Django 5.2.17 on 2026-09-25 13:17

import accounts.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("timezone", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="accounts_user_email_ci_unique",
                    )
                ],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
