# Generated by Django 5.2.17 on 2026-09-25 14:29

import config.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=config.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(default=config.clock.now, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('medical_specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], max_length=16)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='examinations.examinationcategory')),
                ('source_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_occurrences', to='examinations.examinationrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=config.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(default=config.clock.now, editable=False)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('six_months', 'Every six months'), ('yearly', 'Yearly')], max_length=16)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule', to='examinations.examinationrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=config.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(default=config.clock.now, editable=False)),
                ('offset_days', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='examinations.examinationrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='examinationrecord',
            index=models.Index(fields=['user', 'status'], name='examination_user_id_3baa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationrecord',
            index=models.Index(fields=['user', 'scheduled_date'], name='examination_user_id_f3dcfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationrecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'planned', 'completed', 'cancelled', 'missed'])), name='examination_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('interval__in', ['monthly', 'six_months', 'yearly'])), name='recurrence_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('offset_days__gte', 1)), name='reminder_offset_positive'),
        ),
    ]
